logging.level.org.sventetsky.logging.feign.example.client.jsonplaceholder.JsonPlaceHolderClient: DEBUG
logging.level.org.sventetsky.logging.feign.example.client.thereportoftheweek.TheReportOfTheWeekClient: DEBUG
